services: 
  postgres: 
    image: postgres:15 
    container_name: evolution_postgres 
    restart: always 
    environment: 
      - POSTGRES_DB=evolution 
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=1234 
    ports: 
      - "5433:5432" 
    volumes: 
      - evolution_pgdata:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
 
  redis:
    image: redis:7-alpine
    container_name: evolution_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - evolution_redis_data:/data

  evolution_api: 
    image: evoapicloud/evolution-api:v2.3.7
    container_name: evolution_api
    env_file:
      - .env
    restart: always
    ports:
      - "8080:8080" 
    depends_on: 
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./evolution_instances:/evolution/instances
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment: 
      - SERVER_URL=http://72.62.165.89:8080
      - LANGUAGE=es
      - LOG_LEVEL=info
      
      # Autenticación
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=1234
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true

      # Base de Datos
      - DATABASE_ENABLED=true 
      - DATABASE_PROVIDER=postgresql 
      - DATABASE_URL=postgresql://postgres:1234@postgres:5432/evolution?schema=public
      - DATABASE_CONNECTION_URL=postgresql://postgres:1234@postgres:5432/evolution?schema=public
      - DATABASE_CONNECTION_URI=postgresql://postgres:1234@postgres:5432/evolution?schema=public
      - DATABASE_SAVE_DATA_INSTANCE=true
      - DATABASE_SAVE_DATA_NEW_MESSAGE=true
      - DATABASE_SAVE_MESSAGE_INSTANCE=true
      - DATABASE_SAVE_IS_NEW=false

      # Cache & Redis
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_HOST=redis
      - CACHE_REDIS_PORT=6379
      - CACHE_LOCAL_ENABLED=true

      # Proxy Configuration
      - PROXY_ENABLED=true
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_PORT=${PROXY_PORT}
      - PROXY_PROTOCOL=${PROXY_PROTOCOL}
      - PROXY_USERNAME=${PROXY_USERNAME}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
      - HTTP_PROXY=http://${PROXY_USERNAME}:${PROXY_PASSWORD}@${PROXY_HOST}:${PROXY_PORT}
      - HTTPS_PROXY=http://${PROXY_USERNAME}:${PROXY_PASSWORD}@${PROXY_HOST}:${PROXY_PORT}

      # Webhooks Globales
      - WEBHOOK_GLOBAL_ENABLED=true
      - WEBHOOK_GLOBAL_URL=http://72.62.165.89:4000/api/notifications/evolution/webhook
      - WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS=false
      - WEBHOOK_EVENTS_QRCODE_UPDATED=true
      - WEBHOOK_EVENTS_CONNECTION_UPDATE=true
      - WEBHOOK_EVENTS_MESSAGES_UPSERT=true
 
volumes: 
  evolution_pgdata:
  evolution_redis_data:

